name: go-lint
version: 1.1.0
icon: "golang-icon.svg"

inputs:
- name: FLOWCI_GIT_REPO
  type: string
  required: true

docker:
  image: golangci/golangci-lint:v1.21.0

script: |
  cd $FLOWCI_GIT_REPO
  golangci-lint run -v