name: go-lint
version: 1.0.0
icon: "golang-icon.svg"

inputs:
- name: FLOWCI_GIT_REPO
  type: string
  required: true

- name: GOLINT_VERSION
  type: string
  value: v1.21.0
  required: false

- name: GOLINT_CONFIG_FILE
  type: string
  required: false

script: |
  plugindir=${FLOWCI_AGENT_PLUGIN_DIR}/go-lint

  golangci_container_id=$(docker run --rm -dit -w /app golangci/golangci-lint:${GOLINT_VERSION} bash)
  docker cp ${FLOWCI_AGENT_JOB_DIR}/${FLOWCI_GIT_REPO} ${golangci_container_id}:/app
  
  set +e
  docker exec ${golangci_container_id} bash -c 'cd /app/${FLOWCI_GIT_REPO} && golangci-lint run -v'
  exit_code=$(echo $?)
  docker rm -f ${golangci_container_id}
  set -e

  exit $exit_code